/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_googlecode_android_scripting_Exec */

#ifndef _Included_org_qpython_qpysdk_Exec
#define _Included_org_qpython_qpysdk_Exec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_googlecode_android_scripting_Exec
 * Method:    createSubprocess
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_org_qpython_qpysdk_Exec_createSubprocess
  (JNIEnv *, jclass, jstring, jobjectArray, jobjectArray, jstring, jintArray);

/*
 * Class:     org_qpython_qpysdk_Exec
 * Method:    setPtyWindowSize
 * Signature: (Ljava/io/FileDescriptor;IIII)V
 */
JNIEXPORT void JNICALL Java_org_qpython_qpysdk_Exec_setPtyWindowSize
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     org_qpython_qpysdk_Exec
 * Method:    waitFor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_qpython_qpysdk_Exec_waitFor
  (JNIEnv *, jclass, jint);


JNIEXPORT jint JNICALL Java_org_qpython_qpysdk_Exec_nativeInit
        ( JNIEnv*  env, jobject thiz );

JNIEXPORT jint JNICALL Java_org_qpython_qpysdk_Exec_nativeSetEnv
        (JNIEnv*  env, jobject thiz, jstring j_name, jstring j_value);


 int main(int argc, char *argv[])
 {
 }

#ifdef __cplusplus
}
#endif
#endif
